# Generated by Django 3.1.4 on 2021-05-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iapp', '0006_registerfirst'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerfirst',
            old_name='email',
            new_name='remail',
        ),
        migrations.RenameField(
            model_name='registerfirst',
            old_name='name',
            new_name='rname',
        ),
        migrations.RenameField(
            model_name='registerfirst',
            old_name='phone',
            new_name='rphone',
        ),
    ]
